### ISSUE TITLE
Allow importing from a package

### ISSUE THREAD

**Issue by diogolessa** [skovy/typed-scss-modules#103]
I have some package that provides base styles within `.scss` files. When I try to `@import` then from another package and execute `tsm`, I get errors, as explained below:

## Expected Behavior
Should generate types properly

## Current Behavior
Returning the following error (I changed the package name, but the error is the same):
![image](https://user-images.githubusercontent.com/5168901/100618419-96507480-32fa-11eb-8498-9b1893ea79cb.png)

_I tried to use `--includePaths` options poiting to `node_modules` folder, but didn't help._

## Possible Solution
Is it possible to check node_modules folder somehow?

## Steps to Reproduce (for bugs)
1. Create some npm package and provide .scss files in there
2. On another project, install the previous package and `@import` some .scss file from there.
3. Try to run `tsm` on the new project

## Context
I have a style-guide package and I need to use them on another packages.

## Your Environment

- Version used: 3.1.0
- Operating System and versions: Ubuntu 18.04

**Comment by skovy** [comment]
@diogolessa I tested an example roughly like this and running with `--includePaths node_modules` works as expected. Can you confirm you're running it in the correct directory and providing the correct path? For example, if you're in a nested directory it may need to be `--includePaths ../node_modules`? 

If the issue still persists, would you mind creating a minimal example repo so I can try to pinpoint the issue?

**Comment by diogolessa** [comment]
@skovy , thanks a lot. Using only `node_modules` make it works. And you're right, I was pointing to the wrong path, of course.
