### ISSUE TITLE
npx command is incorrect

### ISSUE THREAD

**Issue by fzembow** [skovy/typed-scss-modules#104]
## Expected Behavior

Run the typed-scss-modules script with an npx command

## Current Behavior

Running `npx tsm src` runs [this unrelated package](https://www.npmjs.com/package/tsm)

## Possible Solution

Change readme to `npx typed-scss-modules src` ? Not sure if there's a way to add aliases

**Comment by skovy** [comment]
I removed it entirely because I don't think it makes much sense to run like this since this package has a peer dependency on `node-sass` or `sass`.
