### ISSUE TITLE
tsm --watch --updateStaleOnly tries to read stats before creating file

### ISSUE THREAD

**Issue by ASDFGerte** [skovy/typed-scss-modules#106]
When running as `tsm folder --watch --updateStaleOnly`, a crash `ENOENT: no such file or directory` will occur, after the following steps:

 - create a new scss file
 - save empty
 - tsm will notice (`[ADDED]`), but as it is empty, definitions will be empty, and `[NO GENERATED TYPES]` will happen, and no `.d.ts` file will be generated (which is probably logically the issue, but i am not sure)
 - when changing the file now, this will be noticed (`[CHANGED]`), but `--updateStaleOnly` will try to `const typeDefinitionModified = fs.statSync(path).mtime;` in [write-file.ts](https://github.com/skovy/typed-scss-modules/blob/master/lib/core/write-file.ts), before the `d.ts` file is ever written. `statSync` by default has [`throwIfNoEntry` as `true`](https://nodejs.org/api/fs.html#fs_fs_statsync_path_options), which then causes the crash.

With the before mentioned in mind, there is an easy fix, set `throwIfNoEntry` to `false`, and handle a non-existing file (which should be done either way, a crash shouldn't happen, just because the file doesn't exist, in that scenario). However, there may be a more thorough patch needed, and e.g. an empty file created, when there are no type definitions generated. I am not involved enough to know all implications.

 This may be related to [Issue #38](https://github.com/skovy/typed-scss-modules/issues/38), but as the cause is very specific to `--updateStaleOnly`, it's not identical.

**Comment by hrc7505** [comment]
Facing the same issue

**Comment by skovy** [comment]
@craigrmccown is this something you'd be interested in looking into as part of https://github.com/skovy/typed-scss-modules/pull/99? If not, I can when I have a chance.

**Comment by craigrmccown** [comment]
I'll look into it! This was definitely an oversight on my part.
