### ISSUE TITLE
Bring this to NPM, please

### ISSUE THREAD

**Issue by martin-braun** [skovy/typed-scss-modules#107]
I'd love to this package on NPM, I'm not a Yarn fan.

Thank you!

**Comment by ASDFGerte** [comment]
[Did you try for even a second?](https://www.npmjs.com/package/typed-scss-modules?activeTab=readme)

**Comment by skovy** [comment]
@martin-braun this package is [published on npm](https://www.npmjs.com/package/typed-scss-modules). The `yarn` commands can be swapped out for the equivalent with `npm`:

```bash
npm install -D typed-scss-modules
./node_modules/.bin/tsm src
```

**Comment by martin-braun** [comment]
Thanks mate. I've seen you updated the README already. For some reason I failed when I tried to run it with npx, I guess it was too late at that point. Works like charm! 👍
