### ISSUE TITLE
Semicolon is missing after type definition of  type "styles"

### ISSUE THREAD

**Issue by nomad302** [skovy/typed-scss-modules#111]
## Expected Behavior

we are using the latest version of typed-scss-modules and Eslint for linting in our project. after running the tsm command it generate the types for classes but there is no semicolon after the definition, so when we run lint command , eslint add the semicolon after the type definition.

There should be a semicolon after the type definition for "styles"

command : tsm \"**/*.module.scss\" -w -u -e default -q double --ignore \"node_modules\"

![Screenshot (144)](https://user-images.githubusercontent.com/48388927/106566399-45f1cf00-6556-11eb-88b5-1ca5cbba8471.png)

## Current Behavior
![Screenshot (146)](https://user-images.githubusercontent.com/48388927/106566620-8b160100-6556-11eb-99c7-ecc12bcb4bfa.png)

## Environment

- Version used: v3.4.1 (latest)
- OS: Windows 10
- Linting: typescript-eslint

**Comment by skovy** [comment]
oh wow ha yea we should probably add one

dang, didn't think a missing semicolon would result in a major version, but should probably make this a major bump since the output will change 😕
