### ISSUE TITLE
Does it support :export declarations is sass?

### ISSUE THREAD

**Issue by MrFlashAccount** [skovy/typed-scss-modules#115]
Hello! Thank you for this great tool! As I understand, this tool generates ts declarations for classes, but does it support :export?

**Comment by skovy** [comment]
I did a basic test, and it does appear to work. 

This tool relies on this package: https://github.com/css-modules/css-modules-loader-core in this file: https://github.com/skovy/typed-scss-modules/blob/60ede35dea22fc472baaabe5b75996ecb9ad0173/lib/sass/source-to-class-names.ts.

If it doesn't work as expected, opening a new issue (or, pull request) with a failing unit test (and potential fix) would be appreciated 👍

**Comment by MrFlashAccount** [comment]
@skovy Thank you for the answer!
