### ISSUE TITLE
`--banner` doesn't work with `-e default`

### ISSUE THREAD

**Issue by pbvt** [skovy/typed-scss-modules#117]
## Expected Behavior

Using `--banner '//test'` with `-e default` should work.

## Current Behavior

Using `--banner '//test'` with `-e default` returns this formatting, causing me this error:

![image](https://user-images.githubusercontent.com/78373345/111786018-3f74a800-88b5-11eb-8ae3-8aca5f70bb24.png)

Using `-e named` is fine. If I use `\n` at the end it outputs `//test\n` for both `named` and `default`, but `default` still doesn't add a newline (like it says in the [docs](https://github.com/skovy/typed-scss-modules#--banner)).

## Possible Solution

Based on the current behaviour, `default` must be missing the newline that the `named` code has.

## Steps to Reproduce (for bugs)

1. In `package.json` devDependenices add `"typed-scss-modules": "^4.1.0"`
2. Running `yarn tsm **/*.module.scss --banner '//test' -e default`
3. Running `yarn tsm **/*.module.scss --banner '//test\n' -e default`

## Context

We can use this without the banner so it's not massive but we'd like to make sure that all our generated files have a documenting comment at the top to make it obvious not to manually create them or edit them.

## Your Environment

- Version used: `4.1.0`
- Operating System and versions: Windows 10
- Link to your project: N/A

**Comment by skovy** [comment]
@pbvt thanks for the issue and details, can you confirm the latest version resolves the issue for you?

**Comment by pbvt** [comment]
Yes and no?

So `yarn tsm **/*.module.scss --banner '//test' -e default` works now (and so does `--banner '// THIS FILE...'`) but I worked out this was a minimal example I could boil it down to; my full command now doesn't work as it did before.

My full command is `yarn tsm **/*.module.scss --ignore node_modules/** -e default -p.~@example- packages/ --banner '// THIS FILE...'` and this comes out with:

![image](https://user-images.githubusercontent.com/78373345/111971457-4806f180-8af4-11eb-98f1-b1d56e486a7b.png)

And also, if I save this command as a `package.json` script

```
{
  ...
  "scripts": {
    ...
    "dts": "tsm **/*.module.scss --ignore node_modules/** -e default -p.~@example- packages/ --banner '// THIS FILE...'",
    ...
  }
  ...
}
```

and then run `yarn dts`, I get this different issue:

![image](https://user-images.githubusercontent.com/78373345/111972132-0591e480-8af5-11eb-805c-7e6fba4ff238.png)

**Comment by skovy** [comment]
Hmm, based on that last syntax error it looks like there's an extra leading quote. Based on the examples and tests in this codebase, that shouldn't be happening. The first error I'm not quite sure about.

These both sound like new issues to me, so feel free to open new issues. I can't tell what the issue is based on the options and error without a full reproduction. If you can create a minimal reproducible example (or, a failing test case) to include in those issues, that'd be great.
