### ISSUE TITLE
Further `--banner` issues since `4.1.1`

### ISSUE THREAD

**Issue by philipbushnell-valtech** [skovy/typed-scss-modules#121]
## Expected Behavior

`--banner` should work as expected.

## Current Behavior

`--banner` is causing issues as per comment on https://github.com/skovy/typed-scss-modules/issues/117#issuecomment-803934429.

## Possible Solution

In `4.1.0` my full command just didn't work with `--banner`. In `4.1.1` my full command still works without `--banner` but now using banner causes more issues than just string formatting so it feels like it must be related to the `4.1.1` changes.

## Steps to Reproduce (for bugs)

1. Clone https://github.com/philipbushnell-valtech/typed-scss-modules-banner-issue
2. Run `yarn tsm **/*.module.scss --ignore node_modules/** -e default -p.~@example- packages/ --banner '// THIS FILE...'` and see `-p` break
3. Run `yarn dts` and get yet a different issue:
```
'//
export type Styles = {
  'example': string;
  'exampleTest': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
```

## Context

We can use this without the banner so it's not massive but we'd like to make sure that all our generated files have a documenting comment at the top to make it obvious not to manually create them or edit them.

## Your Environment

- Version used: `4.1.1`
- Operating System and versions: Windows 10
- Link to your project: https://github.com/philipbushnell-valtech/typed-scss-modules-banner-issue (minimal example that gives me the same issues)

**Comment by skovy** [comment]
@philipbushnell-valtech I tried running this command on the codebase you provided and I got this output:

```ts
// THIS FILE...
export type Styles = {
  'example': string;
  'exampleTest': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
```

That looks correct? I see you were using Windows 10, were you using WSL or some other way?

**Comment by philipbushnell-valtech** [comment]
@skovy nope it was just the pure installs on Windows 10. We ended up moving away from scss modules on our project for different reasons anyway so it's no longer something pressing for me. If you can't replicate then feel free to close and I can always reopen if/when we need this in the future.

**Comment by skovy** [comment]
I'll close for now but can re-open if this is an issue for someone else.
