### ISSUE TITLE
Does this package only support scss files or also css files?

### ISSUE THREAD

**Issue by kintz09** [skovy/typed-scss-modules#124]
Does this package offer support for both scss and css files? If not, would you expect one to use `typed-css-modules` package in addition to `typed-scss-modules` package to get declaration files created for all css modules regardless of extension type?

**Comment by skovy** [comment]
@kintz09 I'm not positive. The intention was this package was only to support scss and none of the tests/existing functionality were ever tested on only css files. However, it might work so you could give it a quick try?

If you run into issues, using both packages like you proposed would probably be the easiest.

**Comment by kintz09** [comment]
@skovy I used a glob pattern that included both css and scss files and the type declarations did get created as expected.

I'm not sure how I'd actually go about testing to ensure the css files specifically are working properly, but seems sufficient for my needs.
