### ISSUE TITLE
SCSS type generation 

### ISSUE THREAD

**Issue by marcianosr** [skovy/typed-scss-modules#132]
Hey! 

Thanks for this awesome library! 

I have a question about the following scenario I encountered. Let's say I have a config SCSS file where I define some base SCSS classes and variables I want to use. I import this SCSS file into other SCSS files to use these variables. I don't want to generate types based on the config SCSS, so I ignore the config file. However, in the SCSS files where I import the SCSS config files in I do want types generated, but the classes defined in the config file are now also inherited in the file I import my config file, which I don't want to have types for. 

Code example: 
```
// config.scss

$color: "blue"; 

.baseText {
 font-weight: 400;
}
```

```
// text.scss

@use "./config.scss";

.primary {
 font-size: 50px;
 color: config.$color; 
}
```

```
// text.module.d.ts
export type Styles = {
  primary: string;
  baseText: string; // I don't want this class to be generated as type
};
```

Is it possible to achieve this? I hope my explanation is clear!

Thanks!

**Comment by skovy** [comment]
Hi @marcianosr, as far as I know, there's not currently a way to configure or ignore class names with this tool. However, one approach I'd recommend is separating base styles from your config file. Depending on the build tool, that `baseText` class may be getting duplicated per import which may result in a larger output. Additionally, the base class won't get duplicated by the types either.

For example:

```scss
// config.scss

$color: "blue"; 
```

```scss
// base.scss (or any name)

.baseText {
 font-weight: 400;
}
```

**Comment by marcianosr** [comment]
That was indeed the only solution I could come up with. Thanks for the help :)
