### ISSUE TITLE
Remove `tsm` bin reference

### ISSUE THREAD

**Issue by maraisr** [skovy/typed-scss-modules#134]
## Expected Behavior

https://github.com/skovy/typed-scss-modules/blob/1391aa722eb309c76df6fdc9ce01d2a768984ff2/package.json#L34-L36

read

```diff
  "bin": {
-    "tsm": "./dist/lib/cli.js"
+    "typed-scss-modules": "./dist/lib/cli.js"
  },
```

## Current Behavior

https://github.com/skovy/typed-scss-modules/blob/1391aa722eb309c76df6fdc9ce01d2a768984ff2/package.json#L34-L36

## Possible Solution

```diff
  "bin": {
-    "tsm": "./dist/lib/cli.js"
+    "typed-scss-modules": "./dist/lib/cli.js"
  },
```

## Steps to Reproduce (for bugs)

- `pnpm add tsm`
- `pnpm add typed-scss-modules`

One "owned" package defining that bin (and rightly so), and typed-scss-modules wanting to overrule that. 

## Context

When trying to use `tsm` as a ts-node alt.

## Your Environment

- Version used: 4.1.1
- Operating System and versions: mac
- Link to your project: private

**Comment by skovy** [comment]
It seems reasonable as a breaking change to only allow running the CLI via the full package name as proposed to avoid conflicts and improve clarity.
