### ISSUE TITLE
If you use global variables, there is a problem generating d.ts

### ISSUE THREAD

**Issue by livelyPeng** [skovy/typed-scss-modules#135]
![image](https://user-images.githubusercontent.com/32978177/139817762-17e25010-d54e-4987-b5f5-5eae3eb8e401.png)
![image](https://user-images.githubusercontent.com/32978177/139817781-c1c9afa1-e6cf-4eac-8ac6-d9a6969436bb.png)

**Comment by skovy** [comment]
I believe this is the same issue as https://github.com/skovy/typed-scss-modules/issues/29.
