### ISSUE TITLE
4.1.3 includes breaking binary name change

### ISSUE THREAD

**Issue by ewlsh** [skovy/typed-scss-modules#144]
Would it be possible to unpublish `4.1.3` on `npm`? It includes the breaking change introduced in `v5` and it is a patch version change

As `4.1.3` is over 300 downloads, you'd likely have to contact support (https://docs.npmjs.com/policies/unpublish#issues)

**Comment by ewlsh** [comment]
Alternatively, a deprecation notice could be added 😄

**Comment by skovy** [comment]
I've updated with a deprecation notice: https://www.npmjs.com/package/typed-scss-modules/v/4.1.3
