### ISSUE TITLE
npm install typed-scss-modules(6.2.0) can not run commands 

### ISSUE THREAD

**Issue by nttu94507** [skovy/typed-scss-modules#153]
## Expected Behavior
After npm install typed-scss-modules ,index.scss.d.ts file will be create when enter command tsm src 

## Current Behavior
After npm install typed-scss-modules ,Get system warnning tsm not a command when enter command tsm src,But when I install typed-scss-modules@2.0.1 and it work

## Steps to Reproduce (for bugs)

1.install typed-scss-modules (6.2.0)
2.enter command "tsm src"  
3.Get system warning "'tsm' 不是內部或外部命令、可執行的程式或批次檔。"

- Version used:6.2.0(failed)&2.0.1(done)
- Operating System and versions:windows 11 
- Link to your project:https://github.com/nttu94507/React3

my package.json

{
  "name": "React3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack",
    "lint": "eslint src/*.js",
    "build-css": "node-sass src/index.scss src/index.css",
    "start": "webpack serve",
    "test": "jest --env=jsdom",
    "tsm": "tsm src"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.14.8",
    "@babel/core": "^7.14.8",
    "@babel/plugin-transform-runtime": "^7.17.0",
    "@babel/preset-env": "^7.15.0",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.16.7",
    "@babel/runtime": "^7.14.8",
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.2",
    "@types/react": "^17.0.40",
    "@types/react-dom": "^17.0.13",
    "@types/react-redux": "^7.1.23",
    "@types/react-router-dom": "^5.3.3",
    "@typescript-eslint/eslint-plugin": "^4.29.0",
    "@typescript-eslint/parser": "^4.29.0",
    "babel-loader": "^8.2.2",
    "css-loader": "^6.2.0",
    "eslint": "^7.32.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-react": "^7.24.0",
    "history": "^5.3.0",
    "jest": "^27.5.1",
    "mini-css-extract-plugin": "^2.1.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^12.6.0",
    "style-loader": "^3.2.1",
    "typed-scss-modules": "^2.0.1",
    "webpack": "^5.48.0",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2"
  },
  "dependencies": {
    "@babel/polyfill": "^7.12.1",
    "babel-jest": "^27.0.6",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-test-renderer": "^17.0.2",
    "redux": "^4.1.1",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",
    "uuid": "^8.3.2"
  }
}

**Comment by skovy** [comment]
I'd recommend reading the docs: https://github.com/skovy/typed-scss-modules

Also, when upgrading read the release notes: https://github.com/skovy/typed-scss-modules/releases/tag/v5.0.0

It's no longer `tsm`, it was renamed to `typed-scss-modules` (full package name) to prevent collisions with other packages.
