### ISSUE TITLE
Deprecation of @import

### ISSUE THREAD

**Issue by bryanjtc** [skovy/typed-scss-modules#156]
This is the year @import will be out of support. Are there any plans to support @use?
https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline

**Comment by skovy** [comment]
There are no plans, but contributions are welcomed!

**Comment by skovy** [comment]
There is no extra work needed to support `@use` as this package falls through to the `sass` or `node-sass` package you have installed.

This commit adds a test case and proves that functionality: https://github.com/skovy/typed-scss-modules/commit/44ba5cea9a6478d4dc62275cc069af4fac4980cb

This should work if it already works in your project and everything is configured.
