### ISSUE TITLE
Can't configure aliasPrefixes in the config file

### ISSUE THREAD

**Issue by krzysztof-cislo** [skovy/typed-scss-modules#157]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior

I would like to have all configuration in the config file instead of passing values via cli arguments. 

## Current Behavior

It is not possible to do it because `cliOptions` used [here](https://github.com/skovy/typed-scss-modules/blob/d0a358a3e0c3946a0095aa1bc8116920efface5b/lib/load.ts#L94) contains `{aliasPrefixes: undefined}` which will override value from the config, simply because

`{ ...{aliasPrefixes: {'~': '/src'}}, ...{aliasPrefixes: undefined}}` -> `{aliasPrefixes: undefined}`

## Possible Solution

I am not very familiar with `yargs` package which is used to parse cli params but I guess that it is a way to say that we don't want to have a property set (even with undefined value) if it is not specified in the cli params.

## Your Environment

- Version used: 6.2.0
- Operating System and versions: Windows 11

**Comment by skovy** [comment]
I couldn't find anything googling for the yargs docs, I think we can filter out any `cliOptions` with an `undefined` value before merging and that should resolve this issue.

**Comment by skovy** [comment]
This appears to be a problem with using `coerce` so this only affects `aliases` and `aliasPrefixes`. I think I have a fix.

**Comment by krzysztof-cislo** [comment]
Thank you. I can verify the fix works fine.
