### ISSUE TITLE
Tests are not cross platform

### ISSUE THREAD

**Issue by JohnGurin** [skovy/typed-scss-modules#159]
## Expected Behavior
Tests are reproducible

## Current Behavior
Line endings are inconsistent in tests with `os.EOL`
![image](https://user-images.githubusercontent.com/7195950/163684497-07fd4108-e3e0-4332-8923-d4ebd7d30338.png)

Path resolving are inconsistent in tests
```bash
Expected: StringMatching /C:\Users\John\Documents\typed-scss-modules\__generated__\__tests__\removable.scss.d.ts/
Received: "C:\\Users\\John\\Documents\\typed-scss-modules\\__generated__\\__tests__\\removable.scss.d.ts"
```

## Steps to Reproduce (for bugs)
Clone and yarn install on Windows
## Context
Trying to contribute
## Your Environment
Windows 11 Home
Node 17.9.0
Yarn 1.22.18
Git 2.35.1.windows.2

**Comment by skovy** [comment]
@JohnGurin as I don't work on this directly on Windows this isn't a problem for me, nor CI. If you (or someone else) would like to reproduce, fix, and open a pull request I'll happily accept contributions!
