### ISSUE TITLE
nameFormats.map is not a function 

### ISSUE THREAD

**Issue by herobank110** [skovy/typed-scss-modules#174]
## Expected Behavior

calculate types

## Current Behavior

error log: nameFormats.map is not a function 
type declarations not being output

## Possible Solution

https://github.com/skovy/typed-scss-modules/blob/master/lib/sass/file-to-class-names.ts#L53
missing literal array around nameFormat

## Steps to Reproduce (for bugs)

in typed-scss-modules.config.js:
```
export const config = {
  // nameFormat: 'camel',   commentied out seems to work
  exportType: 'named',
  outputFolder: 'build/@types',
};
```

- Version used: 7.0.0
- Operating System and versions: windows 10

**Comment by skovy** [comment]
Try passing an array: `nameFormat: ['camel']`
