### ISSUE TITLE
--config option

### ISSUE THREAD

**Issue by bryanjtc** [skovy/typed-scss-modules#176]
Is there a --config option to specify the path of the config file?

**Comment by skovy** [comment]
@bryanjtc not currently, but I'd be open to the addition

**Comment by skovy** [comment]
I can't think of a use case where the current configuration (CLI or config file in the same directory this tool is run) would require a different path. I'd be open to considering it with a reasonable use case but without one I'd prefer to avoid adding unnecessary complexity for the sake of it.
