### ISSUE TITLE
Generating declarations

### ISSUE THREAD

**Issue by forabi** [skovy/typed-scss-modules#19]
Whenever I try to build my project, I get:

```
Exported variable 'TimeGridScheduler' has or is using name 'Styles' from external module "./src/styles/styles.module.scss" but cannot be named.
```

Here's the code that's causing the error:

```ts
export type ClassNames = typeof import('./styles/styles.module.scss').default;
```

Any ideas?

**Comment by skovy** [comment]
Are you using `--exportType default`? When I looked at the [default export example](https://github.com/skovy/typed-scss-modules/tree/master/examples/default-export) and added `export type ClassNames = typeof import('./style.scss').default;` on line 2 the `ClassNames` type was equal to `Styles` in this file: https://github.com/skovy/typed-scss-modules/blob/88f11c926bdd0389cc0cdf392c11524144014bf4/examples/default-export/feature-a/index.ts#L1-L4

If you can provide a repo or more code I can dive in a bit more but from a glance using `exportType` of `default` should work 👍 

Additionally, what is the use case for this? I'm thinking the `Styles` type could be exported and then you would be able to change the import like this and use the `Styles` type directly and not have to infer it if you're trying to get that type?

```diff
- import styles from "./style.scss";
+ import styles, { Styles } from "./style.scss";
```

**Comment by skovy** [comment]
I just released https://www.npmjs.com/package/typed-scss-modules/v/0.0.10 which exports the `Styles` and `ClassNames` types when using the `default` `exportType`: https://github.com/skovy/typed-scss-modules#default
