### ISSUE TITLE
Classes used in `:where` (and likely other CSS Selector Level 4) are missing

### ISSUE THREAD

**Issue by ephys** [skovy/typed-scss-modules#197]
## Expected Behavior

say my SCSS is:

```scss
:where(.button) {
  display: block;
}

.disabled {
  opacity: 0;
}
```

The resulting `.d.ts` file should be (in default export mode):

```ts
export type Styles = {
  button: string;
  disabled: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
```

## Current Behavior

The generated `.d.ts` is missing the `.button` class:

```ts
export type Styles = {
  disabled: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
```

## Possible Solution

I'm worried this may be caused by `css-modules-loader-core` not having had updates in 6 years

## Steps to Reproduce (for bugs)

1. Run typed-scss-modules on the CSS files above

## Context

N/A

## Your Environment

- Version used: 7.1.0
- Operating System and versions: MacOS 13.3.1
- Link to your project: N/A

**Comment by skovy** [comment]
@ephys can you please try this version and confirm this issue is fixed for you? https://www.npmjs.com/package/typed-scss-modules/v/7.1.3-alpha.1

I am closing as this should be resolved in this alpha version which will be released in v8.

**Comment by 4-1-8** [comment]
I confirm that it works :-)
