### ISSUE TITLE
Consider adding typescript declaration maps?

### ISSUE THREAD

**Issue by abrouaux** [skovy/typed-scss-modules#198]
## Expected Behavior

When using cmd+click in VSCode (I believe it's go to definition) on a style name, I would like to jump into the SCSS file.

## Current Behavior

VSCode jumps to the .d.ts declaration file, not the scss file.

## Possible Solution

I believe [typescript declaration maps](https://www.typescriptlang.org/tsconfig#declarationMap) would help?

## Your Environment

- Version used: typed-scss-modules 7.1.0
- Operating System and versions: MacOS, VSCode 1.78.0

**Comment by skovy** [comment]
I didn't know about declaration maps, seems like a great option addition!

**Comment by skovy** [comment]
After doing a bit of research, this would be tricky as it would require somehow generating this on the fly. This is a tsconfig setting and since the types are not generated using the TypeScript compiler there isn't a way to general maps on the fly as far as I know.

**Comment by skovy** [comment]
The next step on this would be determining how if at all possible, to generate declaration maps on the fly given an existing source file and existing type definitions. From my research, there is no existing solution out there today.

If someone has a solution (eg: an external package, hooking into the TypeScript compiler API) I'm open to supporting and re-opening this. Given this would require a lot of reverse engineering of how declaration maps work I'm going to close this issue for now.
