### ISSUE TITLE
support modern rgb notation

### ISSUE THREAD

**Issue by lucgagan** [skovy/typed-scss-modules#199]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior

Support modern rgb notation:

```
background: rgb(5 5 5 / 90%);
```

## Current Behavior

```
Function rgb is missing argument $green.
```

**Comment by skovy** [comment]
Without any investigation, this is likely due to `node-sass`/`sass` not handling this syntax. Do you have any additional configuration to handle this when building these styles?

**Comment by skovy** [comment]
No reproduction, and this seems like a general issue with SASS, nothing to do with this tool: https://twitter.com/eriksen_dk/status/1255442528779800576
