### ISSUE TITLE
An error occurred loading the config file

### ISSUE THREAD

**Issue by muzichen** [skovy/typed-scss-modules#201]
![截屏2023-06-26 13 59 27](https://github.com/skovy/typed-scss-modules/assets/7547416/7d712b5b-ee40-45cc-84e7-a083ee122a7c)

**Comment by skovy** [comment]
Template not followed. Try again following the issue template https://github.com/skovy/typed-scss-modules/blob/master/.github/ISSUE_TEMPLATE.md
