### ISSUE TITLE
--listDifferent does not take --ignore into account

### ISSUE THREAD

**Issue by Smona** [skovy/typed-scss-modules#202]
## Expected Behavior

When I run codegen and no files are changed, I would expect running it with `--listDifferent` to pass.

## Current Behavior

If I ignore `**/node_modules/**/*`, no declaration files are generated for scss files included by my node_modules. However, if I run `--listDifferent` with this ignore option, it will fail because those files aren't generated. This makes it hard to verify that types which are tracked in VCS are up to date when checking out those changes.

## Possible Solution

Make the behavior of `--ignore` consistent both with and without the `--listDifferent` option.

## Steps to Reproduce (for bugs)

1. Generate type declarations with some `--ignore` option.
2. Run again with `--listDifferent` and the same `--ignore` option.

## Context

My use case is running a CI job to make sure types are up to date in a checked-out repository, where some SCSS files are gitignored.

**Comment by skovy** [comment]
@Smona do you want to try the latest release?

**Comment by Smona** [comment]
Awesome, thanks for the quick fix!!
