### ISSUE TITLE
Support sass-embedded

### ISSUE THREAD

**Issue by TheAifam5** [skovy/typed-scss-modules#204]
## Expected Behavior

sass-embedded supported.

## Current Behavior

3 years ago node-sass and libsass have been marked as deprecated.

## Possible Solution

Add support for sass-embedded.

**Comment by ccjmne** [comment]
Hey!
I'd like this feature, actually. Do you think there's a change we could reopen this? :)

**Comment by johnnybenson** [comment]
```json
    "devDependencies": {
        "node-sass": "npm:sass-embedded",
        "sass-embedded": "^1.85.1"
    }
```

This might help
