### ISSUE TITLE
Declaration file does not get updated, when the contents of the file is cleared

### ISSUE THREAD

**Issue by pzpsofficial** [skovy/typed-scss-modules#205]
## Expected Behavior

If you clear and save the file in `watch` mode, the corresponding declaration file should be cleared as well.

## Current Behavior

If you use this package in `watch` mode everything works fine, until you want to clear the file. If you do it, you get the message in the terminal `[NO GENERATED TYPES]` but the file still contains old types! Which is misleading.

## Possible Solution

Before showing the error mentioned above, there should be check is a declaration file with this path already exists.

## Steps to Reproduce (for bugs)

1. Setup package and any project using it (in my case Next.js)
2. Create and generate some module files
3. Clear one of them

- Version used: 7.1.2

**Comment by skovy** [comment]
Are you removing (deleting) the file, or clearing the contents so it's an empty file?

**Comment by pzpsofficial** [comment]
I am clearing the file, so it's empty.

**Comment by skovy** [comment]
@pzpsofficial can you try version 7.1.4 and confirm this issue is fixed for you?

**Comment by pzpsofficial** [comment]
Of course, will check it out today!
