### ISSUE TITLE
Prettier isn't applied

### ISSUE THREAD

**Issue by remq** [skovy/typed-scss-modules#219]
## Expected Behavior

After saving a scss file, typed-scss-modules is expected to apply Prettier.

## Current Behavior

When upgrading my project to Prettier version from 3.1.0 to 3.1.1, typed-scss-modules didn't seem to apply Prettier after saving my scss files anymore.

## Possible Solution

I haven't looked into it yet. Might do it at some point, but wanted to report it already. Reverting to Prettier 3.1.0 fixes it.

## Steps to Reproduce (for bugs)

1. Install Prettier 3.1.1
2. Set any rule in the Prettier config that changes the expected output of typed-scss-modules
3. Save a scss file

## Context

N/A

## Your Environment

- Version used: 8.0.0
- Prettier version used: 3.1.1

**Comment by emondpph** [comment]
Yes we just noticed the same issue on our project.

**Comment by skovy** [comment]
Debugging and/or contributions are welcome.

**Comment by Fouzyyyy** [comment]
I will look at it over the weekend

**Comment by gmathieu** [comment]
Hi everyone, 

Here's a [PR](https://github.com/skovy/typed-scss-modules/pull/225) with a fix. 🤞
