### ISSUE TITLE
Is there any way to get the class names?

### ISSUE THREAD

**Issue by JoseFMP** [skovy/typed-scss-modules#24]
The styles come correctly, however, how can we get the class names as strings?
As the definition file is created right now, there is no way to get the class names as strings. i.e. we can do `style.myClass` and get back the style, but there is no way to do `ClassNames.myClass` and get back the class name.

It'd be great to have.

**Comment by skovy** [comment]
@JoseFMP do you have a code sample of what you're trying to do?

Doing `import style from "./style.scss"` will be an object (eg: `{ myClass: "my-class", anotherClass: "another-class" }`) at runtime, but importing `ClassNames` will provide a type that is a union of all the classnames. In this example `ClassNames` will be `"myClass" | "anotherClass"`. `ClassNames` is only a type definition and will not exist at runtime. 

`ClassNames` exists if you want some extra type-safety around using the `style` object and maybe passing it to a function or assigning it to a variable, etc.
