### ISSUE TITLE
--watch stopped working on Windows

### ISSUE THREAD

**Issue by bushmango** [skovy/typed-scss-modules#28]
Still works on my linux machine

**Comment by skovy** [comment]
@bushmango could you provide a few more details? I'm not able to test on a Windows machine.

This is using `chokadir` so I would be curious if you would be able to determine if it's the usage (or incorrect usage) in this library or `chokadir` itself?

**Comment by lkarmelo** [comment]
@skovy 
The issue comes from backslashes in windows paths. I'll send pull request with fix

**Comment by skovy** [comment]
Hey folks, @lkarmelo merged a fix. Mind giving [`v0.0.12`](https://www.npmjs.com/package/typed-scss-modules/v/0.0.12) a go?
