### ISSUE TITLE
Importing variables + mixins

### ISSUE THREAD

**Issue by lfender6445** [skovy/typed-scss-modules#29]
lets say i have page.scss

```scss
// page.scss
@import 'colors'; // this file defines $specialColor variable
@import 'widget';
```

in my widget, i have 

```scss
// widget.scss
body { color: $specialColor } 
```

`tsm` will complain when generating type definition for widget, because i am not importing colors. 

> Undefined variable: "$specialColor". (/tmp/widget.scss)

is there something I can do to get past this issue, other than importing the colors in every widget? 

i would prefer to avoid this as a solution:

```scss
// widget.scss
@import 'colors';
body { color: $specialColor } 
```

**Comment by skovy** [comment]
@lfender6445 I don't think with the current setup you'd be able to achieve that. Do you have any thoughts on what would be the preferable way to resolve the issue?

We could consider adding an `entry` file option, or a `globals` option to define effectively global variables or possible a `insertBefore` that allows you to insert arbitrary code before hand when running which could include `@import 'colors';` or `$specialColor: #000`

**Comment by lfender6445** [comment]
maybe something similar to your `includePaths` but `includeFiles`?

**Comment by lfender6445** [comment]
Actually - does it even matter that there are undefined variables? Does this have any bearing on how the types are generated at all?

Or is the error that the scss cannot compile with the missing variables meaning you cannot generate your type defs

**Comment by skovy** [comment]
@lfender6445 interesting, after thinking about this the problem sounds like `page.scss` is what is being imported as the CSS Module and `widget.scss` is never explicitly imported? (implicitly by other stylesheets).

It sounds like `widget.scss` relies on the "consumer" (importer) to always provide the `$specialColor`? I'd be curious how many distinct files like `widget.scss` you have?

You mention preferring not doing the following:

```scss
// widget.scss
@import 'colors';
body { color: $specialColor } 
```

Would it be more explicit to have the `colors` imported here since `widget.scss` depends on it and not requiring the consumer to import the `colors` in every place before importing `widget`?

Sorry if it's a silly question given I assume there's much more nuance in your codebase but I wanna make sure if a change is made in this package that it's reusable by others and solving the core problem.

**Comment by lfender6445** [comment]
> Would it be more explicit to have the colors imported here since widget.scss depends on it and not requiring the consumer to import the colors in every place before importing widget?

yes, i agree its more explicit (and i prefer the apporach, while some of my team mates find it burdensome to directly specify dependencies), i think the primary issue is that type definitions are being generated for every file including the partials rather than their main compositions or bundles, correct me if i'm wrong but:

```
// page.scss
@import('foo'); // foo.scss
@import('bar'); // bar.scss
```

in this example, we generate 3 type definitions right? 1 for the page, and 2 for its imports?  


what do you think about my previous question though - does it even really matter that an import is missing? in this example 

```
body { color: $specialColor } 
```

the type generator does not really need to know what the value of specialColor is, right? 

it just needs to spit out something like `interface { body: string }`, regardless of my missing imports.

**Comment by skovy** [comment]
> in this example, we generate 3 type definitions right? 1 for the page, and 2 for its imports?

Correct, with the current setup it's looking for all files that match the glob pattern passed in. We could consider adding an ignore param but that could get verbose to use. I believe the truly correct way would be to parse the TypeScript files and traverse all the imports to see what's _actually_ being imported. The current implementation is a bit naive and if it ends with `.scss` we generate the type definitions (which is over generating type definitions).

Going this approach and actually parsing the TypeScript to an AST (or some way to automate finding the import) would be somewhat similar to some of the webpack loaders (but still allow running one-off).

> what do you think about my previous question though - does it even really matter that an import is missing?

No, it doesn't, you're definitely right. I could dig into `node-sass` a bit more and see if there's an easy way to generically catch an error like this and still continue processing and simply replace it with a fixed string or something. The way it works right now is everything gets passed to `node-sass` then we take that output CSS and pluck the classnames and then transform those into type definitions.

**Comment by wildcookie007** [comment]
> > Would it be more explicit to have the colors imported here since widget.scss depends on it and not requiring the consumer to import the colors in every place before importing widget?
> 
> yes, i agree its more explicit (and i prefer the apporach, while some of my team mates find it burdensome to directly specify dependencies), i think the primary issue is that type definitions are being generated for every file including the partials rather than their main compositions or bundles, correct me if i'm wrong but:
> 
> ```
> // page.scss
> @import('foo'); // foo.scss
> @import('bar'); // bar.scss
> ```
> 
> in this example, we generate 3 type definitions right? 1 for the page, and 2 for its imports?
> 
> what do you think about my previous question though - does it even really matter that an import is missing? in this example
> 
> ```
> body { color: $specialColor } 
> ```
> 
> the type generator does not really need to know what the value of specialColor is, right?
> 
> it just needs to spit out something like `interface { body: string }`, regardless of my missing imports.

That's a correct way of perceiving this issue I believe. 

I have found myself struggling against this issue as well, using Webpack with `sass-resource-loader` to import variables globally into all of my `.scss`.

The way I think it might work out is if we could apply a flag that would specify a folder/file from which we could search for those variables.

I've accomplished a similar solution with something like this for my particular problem:

```
// file-to-class-names.ts

fs.readFile(file, 'utf-8', ((err, data) => {
    if (err) {
	throw err;
    }
    const insert = `@import '${path.resolve(__dirname, '../../../src/styles/settings/_variables.scss')}';\n`;
    data = insert + data;
    sass.render(
    {
        file,
        data
    },
    // ...rest of code
```

**Comment by rickiesmooth** [comment]
I'm having the same issues in combination with `sass-resource-loader`

**Comment by skovy** [comment]
@lfender6445 @wildcookie007 @rickiesmooth how would you feel about a `prependData` option that accepts a string?

It would behave in a similar way to the `sass-loaders`'s `prependData` option: https://webpack.js.org/loaders/sass-loader/#prependdata.

Would you all be able to solve your problem with this solution? I don't think it's perfect nor ideal, but it's pretty straightforward as compared to building something more complex that actually builds a dependency graph (or relies on other tools to do so).

**Comment by skovy** [comment]
@lfender6445 @wildcookie007 @rickiesmooth how would you feel about a `prependData` option that accepts a string?

It would behave in a similar way to the `sass-loaders`'s `prependData` option: https://webpack.js.org/loaders/sass-loader/#prependdata.

Would you all be able to solve your problem with this solution? I don't think it's perfect nor ideal, but it's pretty straightforward as compared to building something more complex that actually builds a dependency graph (or relies on other tools to do so).

**Comment by skovy** [comment]
@lfender6445 @wildcookie007 @rickiesmooth how would you feel about a `prependData` option that accepts a string?

It would behave in a similar way to the `sass-loaders`'s `prependData` option: https://webpack.js.org/loaders/sass-loader/#prependdata.

Would you all be able to solve your problem with this solution? I don't think it's perfect nor ideal, but it's pretty straightforward as compared to building something more complex that actually builds a dependency graph (or relies on other tools to do so).

**Comment by wildcookie007** [comment]
> @lfender6445 @wildcookie007 @rickiesmooth how would you feel about a `prependData` option that accepts a string?
> 
> It would behave in a similar way to the `sass-loaders`'s `prependData` option: https://webpack.js.org/loaders/sass-loader/#prependdata.
> 
> Would you all be able to solve your problem with this solution? I don't think it's perfect nor ideal, but it's pretty straightforward as compared to building something more complex that actually builds a dependency graph (or relies on other tools to do so).

Yes, by the looks of it, it should solve mentioned problems or at least to an extent.

**Comment by livelyPeng** [comment]
@skovy 
![image](https://user-images.githubusercontent.com/32978177/139816751-00047e6f-5db6-4892-9f05-3e2f02cea0f9.png)
![image](https://user-images.githubusercontent.com/32978177/139817011-14a186b3-705e-4dd0-a8a3-3516caf3564a.png)
If you use global variables, there is a problem generating d.ts

**Comment by skovy** [comment]
I linked the wrong issue 🤦‍♂️

**Comment by skovy** [comment]
It was renamed to `additionalData` which we can support for this use case: https://webpack.js.org/loaders/sass-loader/#additionaldata

**Comment by skovy** [comment]
Can you all try using the latest release with the `additionalData` config option? https://github.com/skovy/typed-scss-modules#--additionaldata--d
