### ISSUE TITLE
Globbing not searching nested directories.

### ISSUE THREAD

**Issue by dahliacreative** [skovy/typed-scss-modules#33]
Hi, if I run this: `tsm app/react-app/**/*.sass`;

It will find  `app/react-app/some-folder/some-file.sass` but it won't find `app/react-app/some-folder/some-sub-folder/some-file.sass`.

Am I doing something wrong or is this a bug? When ever I've used the `/**/*` globbing pattern before it's always drilled down into sub directories.

Thanks for your help.

**Comment by dahliacreative** [comment]
That fixed it thanks, wasn't seeing that error though :/

**Comment by skovy** [comment]
Interesting, I tested in this repo with:

```
> yarn tsm __tests__/**/*.scss
yarn run v1.17.3
$ ts-node ./lib/cli.ts __tests__/alias-prefixes.scss __tests__/aliases.scss __tests__/complex.scss __tests__/dashes.scss __tests__/empty.scss __tests__/invalid.scss __tests__/nested-styles/style.scss __tests__/style.scss
Only 1 file found for __tests__/alias-prefixes.scss. If using a glob pattern (eg: dir/**/*.scss) make sure to wrap in quotes (eg: "dir/**/*.scss").
Found 1 files. Generating type defintions...
File to import not found or unreadable: ~fancy-import. (typed-scss-modules/__tests__/alias-prefixes.scss[1:1])
✨  Done in 2.05s.
```

And I got the correct warning. I'm going to close this issue for now but if you were able to create a reproducible repo where this warning _didn't_ show up when it _should_ be that would be fantastic to avoid confusion for future people 👍
