### ISSUE TITLE
Feature request: Not to create *.scss.d.ts file if it's empty

### ISSUE THREAD

**Issue by simonchuryakov** [skovy/typed-scss-modules#39]
In my project I have a few common scss files and I don't want to generate `*.scss.d.ts` for them. I can see in output the following logs for them:
```
[NO GENERATED TYPES] styles/colors.scss
[NO GENERATED TYPES] styles/index.scss
[NO GENERATED TYPES] styles/utils.scss
```
If I understand it correctly status `[NO GENERATED TYPES]` means that there was nothing generated for this file.

Could you, please, add the option (for example `--no-empty-files`) to disable file generation in this case?

**Comment by skovy** [comment]
@simonchuryakov if there are no types defined, wouldn't a type error be thrown for missing module definitions when trying to import?

**Comment by simonchuryakov** [comment]
@skovy yes, it would be thrown, but the thing is that we don't need to import the file `colors.scss` with the following content in any `*.tsx` file:
```
$colors: (
    blue: #0000ff,
    red: #ff0000,
);
```
Anyway I've tried to reproduce the described behaviour one more time with updated build script, but no luck. Moreover, I dived into the code where `[NO GENERATED TYPES]` message come from and it looks like there shouldn't be any generated file for my case. So maybe in my case it was generated by mistake when I was playing with my skeleton.

**Comment by skovy** [comment]
Got it, so it's a subset of files that shouldn't generate type declarations?

If you could create a minimum example or create a failing test case I'd be happy to take a look. I understand your case where some files are only variables but that'd be a bit challenging to infer with the current setup I believe.

**Comment by simonchuryakov** [comment]
@skovy as I mentioned before, I couldn't reproduce the issue, and now during closing last-year-survivor items in my task list, I've decided to create a sample app and test the case one more time (if you're interesting in that, please, check this repo - https://github.com/simonchuryakov/nextjs-with-tsm-example).

Everything works perfect, so I guess this issue may be closed.

**Comment by skovy** [comment]
Awesome, I'll go ahead and close this issue. Thanks for following up @simonchuryakov and confirming it's no longer an issue 👍
