### ISSUE TITLE
Consider ignoring node_modules by default

### ISSUE THREAD

**Issue by Ciantic** [skovy/typed-scss-modules#44]
I'd like to make a suggestion: Ignore `node_modules` directory by default. Is there a use case where you want the tsm go inside node_modules? If there is need maybe include option `--include-node-modules`.

Then we could just run "npx tsm", all docs could simply say that too, without the src suffix!

Why I even suggest this trivial change is because I'm in a pickle (🥒) since the next.js framework *enforces the project* to *not* to use a single `src` folder.

Btw, when I started this first time I ran `npx tsm .` and it iterated inside node_modules and did some extra stuff I didn't want.

Thanks for considering, I know that there is nothing wrong with the way tsm is done.

**Comment by skovy** [comment]
@Ciantic how would you feel about having an `--ignore` option? That could then get easily passed to the `ignore` option via [`glob`](https://www.npmjs.com/package/glob). I hesitate to ignore node modules by default since it is possible some variables or other things are potentially used.

**Comment by Ciantic** [comment]
@skovy Great, ignore option would work too. So the idea would be to just write `npx tsm . --ignore node_modules` or perhaps `node_modules/**/*`

**Comment by skovy** [comment]
@Ciantic can you please try the `ignore` option (https://github.com/skovy/typed-scss-modules#--ignore) released in https://www.npmjs.com/package/typed-scss-modules/v/0.0.13?
