### ISSUE TITLE
Change output folder/filename

### ISSUE THREAD

**Issue by oeed** [skovy/typed-scss-modules#56]
Thanks for making this, it's fantastic!

One suggestion I have is somehow having a way to change the output folder or filename. I'm not sure exactly how it should work, but essentially my end goal is to put them in a '__generated__' folder in the same directory which I already use for other generated typings (GraphQL queries).

Hiding the files isn't too bad, so it's by no means a deal-breaker, but would be nice to have 😄

**Comment by skovy** [comment]
Could you create a minimal example? Would that still type check properly?

Having a minimal example would be hugely helpful to use as a test case! 👍

**Comment by oeed** [comment]
Yeah sure, here's a fairly minimal outline, but if you want a more fleshed out one let me know.

Essentially, when outputting the type definitions you could wrap it in a module using the path of the SCSS file. Once you do that the types file can basically go anywhere or be called anything as long as your tsconfig is set properly (i.e. anywhere .d.ts files are detected).

```typescript
declare module "app/components/test.module.scss" {
  export const classOne: string;
  export const classTwo: string;
  // etc
}
```

I can see it getting a little complicated to do and manage, so understandable if it's not desired though.

**Comment by skovy** [comment]
Ah right, yea I think this seems reasonable.

Could you also provide what you would imagine as the expected
file/directory output?

**Comment by oeed** [comment]
Sure, so perhaps an example folder would look like this:
```
src/
  example/
    test.component.tsx
    test.module.scss
    __generated__/
      test.module.scss.d.ts
```

or alternatively this (i.e. having it flexible to suit either scenario would be ideal):

```
src/
  example/
    test.component.tsx
    test.module.scss
    test.module.generated.d.ts
```

**Comment by Elvincth** [comment]
Any updates?

**Comment by skovy** [comment]
I don't believe outputting a different file name will work in practice. You can refer to the linked PR to see how a generated output folder can be supported. For this to work, the directory structure needs to match the project and the generated directory needs to be added to the `rootDirs` for TypeScript to properly map these generated types to the actual files.

**Comment by skovy** [comment]
@oeed @Elvincth can you try the latest release that adds the `outputFolder` option? https://github.com/skovy/typed-scss-modules/releases/tag/v6.1.0

See the docs for more details: https://github.com/skovy/typed-scss-modules#--outputfolder--o
