### ISSUE TITLE
Feature Request: Delete old .d.ts files that do not have .scss files anymore

### ISSUE THREAD

**Issue by PetersonRyan** [skovy/typed-scss-modules#61]
Feature Request:

After deleting a .scss or .sass file I would like this tool to automatically remove the corresponding .d.ts file on the next run.

**Comment by skovy** [comment]
@PetersonRyan do you have thoughts on how something like this would be implemented?

I can't think of a simple way to generically apply this logic. For example: if we delete any `*.d.ts` file that doesn't have a corresponding output this could unintentionally delete unrelated type definitions (`*.d.ts` files).

**Comment by PetersonRyan** [comment]
@skovy Sorry for the late reply.

I was thinking it would only apply to `*.scss.d.ts` or `*.sass.d.ts` files, instead of any `*.d.ts` file. It could be optional and triggered with a flag. Additionally, for extra redundancy, while using the `--watch` flag it would know which files it has generated itself, and therefor which files are safe to delete.

**Comment by ccortezaguilera** [comment]
@skovy hello, do you mind if I try to create a pull request for this change?

**Comment by skovy** [comment]
@ccortezaguilera yea, if you'd like to give this a shot that'd be great!

Do you have a general idea of how you're planning to implement this? I could imagine this being potentially destructive (deleting files) and potentially resource intensive (many files to watch).

**Comment by ccortezaguilera** [comment]
@skovy Thanks! Yeah I think I already have a PR ready. The approach I'm using is the FS unlink event for when files are removed and then trying to minimize the files looked at when just running the cli without the --watch flag. I think the explanation will be clearer when looking at the code.

**Comment by skovy** [comment]
@PetersonRyan mind giving the latest version a try? https://github.com/skovy/typed-scss-modules/releases/tag/v3.3.0

I'm going to close this issue since the only feasible solution is to do this while watching which is what @ccortezaguilera has implemented.

**Comment by PetersonRyan** [comment]
@skovy works well for me!

Thanks @ccortezaguilera for implementing this 👍

**Comment by skovy** [comment]
Awesome, great to hear!
