### ISSUE TITLE
CRLF for line endings of generated .d.ts files

### ISSUE THREAD

**Issue by pajohns** [skovy/typed-scss-modules#67]
Currently when building scss types, the generated *.d.ts files have line endings with `LF`. Git, by default, uses `CRLF` for line endings so whenever the module builder runs all .d.ts files are flagged as having changed.

## Expected Behavior
An option should be provided where line ending is a configurable parameter. Alternatively CRLF is the default line ending format.

## Current Behavior
All line endings are currently LF only.

## Your Environment
React 16.13.1
Sass 1.26.3
Windows 10
Visual Studio Code

**Comment by pajohns** [comment]
I haven't been able to consistently reproduce this issue, but leaving it open as it is something that has been present previously. I'll add more information as I find it.

**Comment by skovy** [comment]
@pajohns any new details, or can we close this issue?

**Comment by pajohns** [comment]
@skovy this issue is still present. I remember looking at the source code on this and noticed that each line ending is done programatically, so there shouldn't be too much involved to change line endings to use `LF` instead of `CRLF`. It would be good for git to not pick up the generated .d.ts files every time there's a rebuild.

**Comment by skovy** [comment]
Fixed by #94 

@pajohns would you mind updating to the latest version and confirming?
