### ISSUE TITLE
Attempting to use prettier breaks listDifferent functionality

### ISSUE THREAD

**Issue by nperez0111** [skovy/typed-scss-modules#88]
## Expected Behavior

When using listDifferent it should try to compare the outputs of the prettier-ified result to what is in the file system.

## Current Behavior

Prettier can result in different formatting than default resulting in listDifferent always returning false

## Possible Solution

Prettier probably has a programmatic API to be able to compare results as strings.

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Context

Updating to 3.1.0 broke my build because prettier formats my file to always use semi-colons.

## Your Environment

- Version used:3.1.0 (previous working version 3.0.0)
- Operating System and versions: macOS but irrelevant
- Link to your project:

**Comment by skovy** [comment]
Ah, didn't think of this. I'll work on a fix. I've opened a PR with a failing test case in the meantime to validate.

**Comment by skovy** [comment]
@nperez0111 can you please try the latest release?

**Comment by nperez0111** [comment]
It works correctly now @skovy Thanks for making the changes!
