### ISSUE TITLE
Request: Ability to define an alias prefix

### ISSUE THREAD

**Issue by dawnmist** [skovy/typed-scss-modules#9]
If using the Webpack sass-loader, to import an scss file from a node_modules package the usual scss import is `~<moduleName>/path/to/file`, e.g. `~bootstrap-sass/lib/bootstrap`. See https://github.com/webpack-contrib/sass-loader#imports

At present, using aliases means that a unique alias needs to be defined for every used node_modules scss import. This very quickly gets unwieldy, e.g.
```sh
tsm src \
  --aliases.~bootswatch/slate/variables node_modules/bootswatch/slate/variables \
  --aliases.~bootstrap-sass/assets/stylesheets/bootstrap node_modules/bootstrap-sass/assets/stylesheets/bootstrap \
  --aliases.~bootswatch/slate/bootswatch node_modules/bootswatch/slate/bootswatch \
  --aliases.~react-widgets/lib/scss/react-widgets node_modules/react-widgets/lib/scss/react-widgets
```
especially when it needs to be embedded in a package.json script (forcing it to be all on one-line).

Request: ability to define a prefix to replace, e.g.
```sh
tsm src --aliasPrefixes.~ node_modules/
```
where every import beginning with the prefix string has that string replaced with the given replacement, so `~bootswatch/slate/variables` would become `./node_modules/bootswatch/slate/variables`.

**Comment by skovy** [comment]
The associated PR was merged and closes this out 👌
