### ISSUE TITLE
watch is "watching" wrong files

### ISSUE THREAD

**Issue by theKashey** [skovy/typed-scss-modules#97]
## Expected Behavior

watch more works
## Current Behavior

Running a command
```
$ tsm "packages/**/*.scss" --ignore node_modules --exportType default -n none -w
```
generates the following output
```
Watching files...
[ADDED] packages/uikit/styles/_index.scss
[ADDED] packages/uikit/styles/mixin.scss
[ADDED] packages/uikit/styles/theme.scss
[NO GENERATED TYPES] packages/uikit/styles/_index.scss
[NO GENERATED TYPES] packages/uikit/styles/mixin.scss
[NO GENERATED TYPES] packages/uikit/styles/theme.scss
[ADDED] packages/uikit/styles/node_modules/.bin/acorn
```
^^^ note the wrong file added

After that, the process is doomed

```
expected "{".
  ╷
1 │ #!/usr/bin/env node
  │  ^
  ╵
  packages/uikit/styles/node_modules/.bin/acorn 1:2
```

## Your Environment

- Version used: 3.2.2

**Comment by theKashey** [comment]
`--ignoreInitial` is solving the problem.
Sounds like this is more `chokidar` API problem, which might "see" more files than it should.
However simple re-glob-ing file in `change`/`add` callback might save the day.

**Comment by skovy** [comment]
Yea, this seems like an issue with `chokadir` 🤔 

I wonder if it's related to these issues relating to symlinks: https://github.com/paulmillr/chokidar/issues/544 & https://github.com/paulmillr/chokidar/issues/967

I actually didn't realize the node module `.bin` files are symlinks, but makes sense.

I think a stop-gap solution like you said by doing a re-check against the glob could solve the immediate issue, although unfortunate.

**Comment by skovy** [comment]
Closing this issue since it's stale and an issue with a dependency, not this package.

However, if this is still an issue (`chokadir` was updated) I wonder if using the ignore option could help? https://github.com/skovy/typed-scss-modules#--ignore

I haven't tried, but maybe something like `--ignopre 'node_modules/.bin/*'`?
